mkdir build && cd build

cmake -G "Visual Studio 16 2019" -A x64 ^
 -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" ^
 -DCMAKE_BUILD_TYPE=Release ^
 -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -DCMAKE_SYSTEM_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -DLIBXML2_LIBRARIES="%LIBRARY_PREFIX%\lib\libxml2.lib" ^
 -DBOOST_LIBRARYDIR="%LIBRARY_PREFIX%\lib" ^
 -DBOOST_INCLUDEDIR="%LIBRARY_PREFIX%\include" ^
 -DOCC_INCLUDE_DIR="%LIBRARY_PREFIX%\include\opencascade" ^
 -DOCC_LIBRARY_DIR="%LIBRARY_PREFIX%\lib" ^
 -DBUILD_SHARED_LIBS=Off ^
 -DCOLLADA_SUPPORT=Off ^
 -DBUILD_IFCPYTHON=Off ^
 -DBUILD_EXAMPLES=Off ^
 -DBUILD_GEOMSERVER=Off ^
 -DBUILD_CONVERT=Off ^
 ../cmake
 
@REM if errorlevel 1 exit 1

cmake --build . --target INSTALL --config Release

@REM if errorlevel 1 exit 1
