mkdir build && cd build

# this disables linking to python DSO
if [ `uname` == Darwin ]; then
    export  LDFLAGS="$LDFLAGS  -Wl,-flat_namespace,-undefined,suppress"
fi

cmake -G "Ninja" \
 -DCMAKE_BUILD_TYPE:STRING=Release \
 -DCMAKE_INSTALL_PREFIX:FILEPATH=$PREFIX \
 -DCMAKE_PREFIX_PATH:FILEPATH=$PREFIX \
 -DCMAKE_SYSTEM_PREFIX_PATH:FILEPATH=$PREFIX \
 -DOCC_INCLUDE_DIR:FILEPATH=$PREFIX/include/opencascade \
 -DOCC_LIBRARY_DIR:FILEPATH=$PREFIX/lib \
 -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON \
 -DCOLLADA_SUPPORT:BOOL=OFF \
 -DBUILD_EXAMPLES:BOOL=OFF \
 -DBUILD_IFCPYTHON:BOOL=OFF \
 -DBUILD_GEOMSERVER:BOOL=OFF \
 -DBUILD_CONVERT:BOOL=OFF \
 -DENABLE_BUILD_OPTIMIZATIONS=ON \
 -DLIBXML2_INCLUDE_DIR:FILEPATH=$PREFIX/include/libxml2 \
 ../cmake

ninja install
