package:
  name: ifcopenshell
  version: "0.6.0"

source:
  git_rev: "main"
  git_url: https://github.com/WouRaoyu/IfcOpenShell.git

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake 3.17.0

  host:
    - boost-cpp 1.72.0 *
    - icu 64.2 *
    - occt 7.4.0 *

  run:
    - boost-cpp 1.72.0 *
    - icu 64.2 *
    - occt 7.4.0 *

about:
  home: http://ifcopenshell.org
  license: LGPL
